CLASS zcl_salesorder_operation_u_02 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_salesorder_operation_u_02 IMPLEMENTATION.
ENDCLASS.
